spring.application.name=pc1repaso
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
logging.level.org.springframework.web.client.RestTemplate=DEBUG
spring.jpa.hibernate.ddl-auto=create-drop
jwt.secret=${JWT_SECRET}
jwt.expiration-access=${JWT_EXPIRATION_ACCESS}
jwt.expiration-refresh=${JWT_EXPIRATION_REFRESH}